parameters:
  - name: repoName
    type: string

  - name: dllName
    type: string

steps:
- pwsh: '$(scriptsDirectory)/copy-dotnet-models.ps1'
  displayName: 'Update models'
  env:
    BuildConfiguration: $(buildConfiguration)
    OutputFullPath: $(typewriterDirectory)/output
    RepoModelsDir: $(Build.SourcesDirectory)/${{ parameters.repoName }}/src/Microsoft.Graph/Generated/

- pwsh: dotnet build ${{ parameters.repoName }}/**/*.csproj --configuration $(buildConfiguration)
  displayName: Build ${{ parameters.dllName }}
