steps:
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'kiota'
    downloadPath: '$(Build.SourcesDirectory)'

- bash: chmod +x $(Build.SourcesDirectory)/kiota/kiota
