# designed to have a single run (single output directory)
parameters:
- name: openAPIDescription
  type: string

- name: targetNamespace
  type: string

- name: targetClassName
  type: string

- name: language
  type: string

- name: version
  type: string

- name: repoName
  type: string

- name: branchName
  type: string

- name: languageSpecificSteps
  type: stepList
  default:
  - pwsh: |
      Write-Error "No language specific step is provided"

- name: cleanMetadataFile
  type: string

- name: cleanMetadataFolder
  type: string

steps:
- template: set-up-for-generation.yml
  parameters:
    cleanMetadataFolder: ${{ parameters.cleanMetadataFolder }}

- checkout: ${{ parameters.repoName }}
  displayName: 'checkout ${{ parameters.repoName }}'
  fetchDepth: 1
  persistCredentials: true

# need this for the shared scripts (maybe we should move them to msgraph-metadata)
# no need for recursive, just scripts from the main repo
- checkout: self
  displayName: 'checkout generator'
  fetchDepth: 1
  persistCredentials: true

- pwsh: '$(scriptsDirectory)/create-branch.ps1'
  displayName: 'Create a branch in ${{ parameters.repoName }}'
  env:
    RepoDirectory: $(Build.SourcesDirectory)/${{ parameters.repoName }}
    BranchName: ${{ parameters.branchName }}
  workingDirectory: ${{ parameters.repoName }}

- bash: '$(kiotaDirectory)/kiota --openapi ${{paramters.openAPIDescription}} --language ${{ parameters.language }} -o $(kiotaDirectory)/output -n ${{ parameters.targetNamespace }} -c ${{ parameters.targetClassName }}'
  displayName: 'Run Kiota for ${{ parameters.language }} ${{ parameters.version }}'

- ${{ parameters.languageSpecificSteps }}

- pwsh: '$(scriptsDirectory)/git-push-files.ps1'
  displayName: 'Git: push generated files'
  env:
    BranchName: ${{ parameters.branchName }}
    PublishChanges: $(publishChanges)
    OverrideSkipCI: $(overrideSkipCI)
  workingDirectory: ${{ parameters.repoName }}
