steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 5 (typewriter)'
  inputs:
    packageType: sdk
    version: 5.0.100
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 6 (kiota)'
  inputs:
    packageType: sdk
    version: 6.0.100
    installationPath: $(Agent.ToolsDirectory)/dotnet
